# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e36a562eed4327e23f8cf0117583256d6374f22d06096c220222dc0052cecdf76985d38a28951bd93b472a1f0768e4e18a008537438d2800153556005f21ad79

test:
  secret_key_base: 91bcc9ec01950abfcf264a3a06e7dddf14e2d74d6a04d16365f994dea670560d142b1d53076b08f0a483305b3065d76522b0a2255144bc405219e6bcdc48231c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
